OPENCV_PATH = -I/usr/local/include -I/usr/local/include/opencv -lpthread -lrt -lm -lopencv_highgui -lopencv_core -lopencv_imgproc -lopencv_contrib -lopencv_calib3d -lopencv_features2d -lopencv_video

cam: car2.c
	gcc car2.c -o car1234 -O2 $(OPENCV_PATH)
#	g++ capture.cpp -o cap -O2 $(OPENCV_PATH)
#v4l2: v4l2.c
#	gcc v4l2.c -o v4l2 -O2 $(OPENCV_PATH)
